### ISSUE TITLE
code

### ISSUE THREAD

**Issue by N-cunningham** [EamonCullen/CT417AssignmentPartB#1]
BufferedReader br = new BufferedReader(new FileReader(csvFile));
while ((line = br.readLine()) != null) {
    // use comma as separator
    String[] cols = line.split(cvsSplitBy);
    System.out.println("Coulmn 4= " + cols[4] + " , Column 5=" + cols[5]);
}

**Comment by EamonCullen** [comment]
thanks i needed this
